[package]
name = "small_cage"
version = "0.1.0"
edition = "2024"

[dependencies]
aes = "0.8.4"
aes-gcm = "0.10.3"
colored = "3.0.0"
ctrlc = "3.5.1"
dialoguer = "0.12.0"
env_logger = "0.11.8"
figlet-rs = "0.1.5"
indicatif = "0.18.3"
log = "0.4.28"
x25519-dalek = "2.0.1"
